# Generated by Django 3.1.2 on 2020-10-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorder',
            name='audio',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='recorder',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0),
        ),
    ]
