# Generated by Django 3.1.2 on 2020-10-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201020_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recorder',
            new_name='RecorderModel',
        ),
    ]
